### ISSUE TITLE
Add patch property for fuzz value

### ISSUE THREAD

**Issue by dooug** [netresearch/composer-patches-plugin#13]
In some cases, the patch command might need a higher fuzz value (or other arguments) to apply correctly. Currently this isn't possible, so the patch will be rejected and reverted. 

I'm working on a fix for this in my fork: https://github.com/dooug/composer-patches-plugin/tree/feature-apply-patch-fuzz 
The branch name is misleading, this could be used to add any additional patch command arguments with the 'args' property. 

Example use: https://gist.github.com/dooug/f57ac71951b964461530

```
            "extra": {
              "patches": {
                "drupal/apachesolr": {
                  "7.1.6": [
                    {
                        "title": "allow the sort block to show despite no/1 result.",
                        "url": "https://www.drupal.org/files/issues/apachesolr-expose-minimum-sort-1421510-8.patch",
                        "args": " -F5"
                    }
                  ]
                }
              }
            }
```

bad example though, I think it applies without the extra fuzz. This demonstrates the `args` property though.

**Comment by copitz** [comment]
Thank you dooug! Merged and documented :)

**Comment by dooug** [comment]
@copitz, Thanks for the quick response!
