### ISSUE TITLE
Applying multiple patches to same a package results in second patch applied multiple times.

### ISSUE THREAD

**Issue by generalredneck** [netresearch/composer-patches-plugin#19]
I'm using Version 1.2.0. I have a package that I'm applying 2 patches to. I also have a process that every time I update my code, I do a composer install. This has proven to be problematic. For reference, this is my package in composer.json... Note for simplicity sake I'm only putting part of the package def in here.

         {
            "type": "package",
            "package": {
                "name": "promet/martincounty-patches",
                "version": "1.3.0",
                "type": "patches",
                "require": {
                    "drupal/google_analytics": "7.2.1",
                    "netresearch/composer-patches-plugin": "~1.0"
                },
                "extra": {
                    "patches": {
                        "drupal/google_analytics": {
                            "7.2.1": [
                                {
                                    "title": "Fixing issue with Undefined Index: Value in googleanalytics_page_alter() Line 217",
                                    "url": "https://www.drupal.org/files/issues/googleanalytics-2392371-10.patch"
                                },
                                {
                                    "title": "Allow Altering of Information sent to GA",
                                    "url": "https://www.drupal.org/files/issues/google_analytics-allow_alter_of_page_url_sent_to_ga-2571429-1.patch"
                                }
                            ]
                        }
                    }
                }

Since this package was updated, I've run composer install 6 times. The second patch adds one line. That line has been duplicated 6 times:
![Alt text](https://monosnap.com/file/JopPJa2WT3EacZFRKuAqYez6nUF7bf.png)

This is the -vvv output when debugging:

```
Downloading https://www.drupal.org/files/issues/google_analytics-allow_alter_of_page_url_sent_to_ga-2571429-1.patch
  Testing patch 3944b0c7b9b7eec411804a2247aeae143a51541d on drupal/google_analytics: Fixing issue with Undefined Index: Value in googleanalytics_page_alter() Line 217
  Testing patch a557a69a763f247ffa3a2321340032b9d92fec6e on drupal/google_analytics: Allow Altering of Information sent to GA
  Applying patch a557a69a763f247ffa3a2321340032b9d92fec6e to drupal/google_analytics: Allow Altering of Information sent to GA
```

I think there is a problem in testing the patch...

**Comment by generalredneck** [comment]
So it appears that this patch CAN be applied multiple times per the "runCommand" function. I think it might be ideal to figure out how to flag a patch as "installed" on a package. Do you know if this is possible? I've not wrote any composer plugins sophisticated enough to need to store state.

**Comment by copitz** [comment]
Hi @generalredneck ,

thanks for your report. I tried the patch and can prove the behaviour. This is because the patch commands works with a fuzz factor by default, which in your patches case leads to doubled applications of the patch. The quick solution for you would be to simply set the fuzz factor for this patch to 0 or 1:

    {
        "title": "Allow Altering of Information sent to GA",
        "url": "https://www.drupal.org/files/issues/google_analytics-allow_alter_of_page_url_sent_to_ga-2571429-1.patch",
        "args": "-F 0"
    }

I wouldn't like to keep track of the patches in any additional file as the complete process would fail without this file. However if it should show up that it's really required I'd probably have to (or try to add it to the composer.lock). Anyway I'm thinking about adding the `-F 0` as a default option.

**Comment by generalredneck** [comment]
interesting... This would be an acceptable solution... obviously, when patches are applied on patches, this may cause an issue... but that's something that has to be dealt with anyway... at which point we just go make a fork. :+1: 

Thanks for the help!
