### ISSUE TITLE
Generate PATCHES.txt

### ISSUE THREAD

**Issue by boombatower** [netresearch/composer-patches-plugin#21]
Any possibility in generating a PATCHES.txt file in the base directory of every patched package?

Simple list of the urls of patches applied for easy checking when browsing the source tree?

**Comment by copitz** [comment]
It should be possible - but there's no method for that yet.

Best would probably be to provide a script for that or hook into composer status or show - it just might take a while until I find the time to do that...

**Comment by ngolatka** [comment]
Closed due to inactivity.
