### ISSUE TITLE
Patch gets applied everytime composer install is run

### ISSUE THREAD

**Issue by davidbarratt** [netresearch/composer-patches-plugin#22]
I've never seen this problem before, but for some reason, this patch:
https://www.drupal.org/files/issues/contact_storage-default_redirect-2629630-2.patch
gets applied everytime `composer install` is run, even if's already been applied.

Here's my composer.json file:
https://github.com/phototech/sailvenice/blob/develop/composer.json

If you run `composer install` the first time, it applies the patch like it's supposed to, if you run `composer install` again, it will again apply the patch (which causes a PHP syntax error). :(

I'm not sure what's cuasing the problem with this patch specifically, but the only work around I've found is to delete the `web/modules/contrib/contact_storage` completely and then run `composer install` again. :(

**Comment by davidbarratt** [comment]
You can see here where it's applying it even though there's nothing to install or update:
https://travis-ci.org/phototech/sailvenice/builds/110859483#L636

**Comment by copitz** [comment]
It might be that the fuzz level is too big - can you try reducing it like [here](https://github.com/netresearch/composer-patches-plugin/issues/19#issuecomment-141923488)?

**Comment by davidbarratt** [comment]
@copitz,

That fixed my problem! thanks!
