### ISSUE TITLE
patch does not have parameter --no-backup-if-mismatch on FreeBSD

### ISSUE THREAD

**Issue by andreaswolf** [netresearch/composer-patches-plugin#24]
The tool `patch` does not have the parameter `--no-backup-if-mismatch` on FreeBSD (10.3-p5), therefore applying patches currently fails in my production environment.

I’m not sure if there is a reliable way of detecting that parameter besides parsing the output of `patch --help`, but I also think that parameter can be totally skipped if we do a dry run before actually applying it.

**Comment by Techwolf12** [comment]
Same one here: https://github.com/cweagans/composer-patches/pull/184

**Comment by ngolatka** [comment]
Closed due to inactivity.
