### ISSUE TITLE
Caching patch content

### ISSUE THREAD

**Issue by dudilag** [netresearch/composer-patches-plugin#25]
Caching patches content cause problems with reverting / applying, when patch content is changed.
Case:
All patches are in a separate repository, which is required by main repository with project.

On main repository
1. add "patch repository" to required
2. composer update - patches have been applied properly
3. change patch A content in the "patch repository" and update main composer.json
4. composer update
4.a - reverting patches (caching patch content)
4.b - changing branch / tag on "patch repository" 
4.c - apply patches (patch content is taken from the cache, not from the files - which are changed)

**Comment by vergissberlin** [comment]
**Hello @dudilag,**

thank you for contributing!

**Comment by ngolatka** [comment]
Linked PR has been merged, closing this issue.
