### ISSUE TITLE
GPL Licensing

### ISSUE THREAD

**Issue by lstrojny** [netresearch/composer-patches-plugin#28]
I have two questions regarding licensing:

 - Was picking the GPL v2 as a license a conscious choice and if so, would you be open to/would it be possible to change that to a more permissive license (Apache, BSD)?
 - What do you consider derivative work in that context that would be affected by the derivative work clause of the GPL? The composer.json? The whole application?

Sorry for the boring questions on a Friday afternoon.

**Comment by CybotTM** [comment]
Projects using this plugin are not considered "derivative work".

"derivative work" is when changing the source code for this plugin, or create a new piece of software based on the source code of this plugin.
