### ISSUE TITLE
Add documentation about patches in local files

### ISSUE THREAD

**Issue by PhoneixS** [netresearch/composer-patches-plugin#38]
I think it could be good to have an example of how to use patches in local files as it could be confusing at first.

For example, in my case, I have added a new package in `composer.json` like:

```
"repositories": [
        {
            "type": "package",
            "package": {
                "type": "metapackage",
                "name": "vendor/package-patches",
                "version": "1.0.0",
                "require": {
                    "netresearch/composer-patches-plugin": "~1.0"
                },
                "extra": {
                    "patches": {
                        "zohocrm/php-sdk":     [
                            {
                                    "title": "Corregir warning 'Array and string offset access...' en el logger.",
                                    "url": "parches/fixzohologgerwarning.patch"
                            }
                        ]
                    }
                }
            }
        }
    ],
   "require": {
        ....
        "php-64bit": ">=7.3.0",
        "zohocrm/php-sdk": "^1.1",
        "vendor/package-patches": "~1.0"
    },
```

I have also added a new folder at the same level as the `composer.json` called "parches" and add a patch file `fixzohologgerwarning.patch` like:

```
# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/src/com/zoho/crm/library/exception/Logger.php
+++ b/src/com/zoho/crm/library/exception/Logger.php
@@ -6,7 +6,7 @@
 	{
 		set_include_path(ZCRMConfigUtil::getConfigValue('applicationLogFilePath'));
 		$path=get_include_path();
-		if($path{strlen($path)-1}!='\/')
+		if($path[strlen($path)-1]!='\/')
 		{
 			$path=$path."/";
 		}


```

Note that the patch will be called with the option `-p1` (remove the first slash) and in the directory of the library.

Then run the commands to update the dependency and to install patches:

```
composer update vendor/package-patches
composer install
```

**Comment by PhoneixS** [comment]
The update of the documentation have been already asked in the issue https://github.com/netresearch/composer-patches-plugin/issues/5

**Comment by ngolatka** [comment]
@Gitsko : Please see the last comment at the issue #5 from allanpaiste. I think that's a valid question. There should indeed be an example in the doc how to use a local patch.

However, I don't feel qualified to write that part of the doc. Can you do it, based on the above example from @PhoneixS ?

**Comment by Gitsko** [comment]
Hi @PhoneixS,

👍  thanks for your help, I have adopted the documentation in https://github.com/netresearch/composer-patches-plugin/commit/0d86e604ff481cc726881e0028f1cd5b193abbc9 .
