### ISSUE TITLE
Apply patch to installed dependency.

### ISSUE THREAD

**Issue by andrewholgate** [netresearch/composer-patches-plugin#4]
So far this great tool has been able to handle everything I need in patching dependencies except for one.

I am trying to apply a new patch to an already installed project dependency. I added a new patch `composer.json` and ran `composer update` but it does not recognise the new patch unless I remove the `vendor/` directory.

Is it possible to apply a patch to an already installed project dependency?

**Comment by pcambra** [comment]
I think you can accomplish this, either upgrading the version of your package (1.0.0 -> 1.0.1) if you're using ~1.0 as dependency or you can just have * as dependency of your patches package and it will always get the whole set. I encountered #6 while using this technique, though.

**Comment by copitz** [comment]
Hi, thanks for your feedback and sorry for the late reply. I think pcambra is right and thus close this issue in favor of #6
