### ISSUE TITLE
Apply locally stored patch

### ISSUE THREAD

**Issue by Rbn3D** [netresearch/composer-patches-plugin#5]
How can I install a patch from a local folder, and not an url?

**Comment by copitz** [comment]
You can use absolute paths or paths relative to the application root - just use them instead of the url. It seems (means I did not test it) that you currently can't use paths relative to the package directory.

**Comment by dutchiexl** [comment]
I get this error: file could not be downloaded: failed to
  open stream: No such file or directory

<code>{
                  "title": "Fixes the ckeditor version not found problem.",
                  "url": "/patches/locale_throwing_notice.patch"
                }</code>

**Comment by copitz** [comment]
dutchiexl, in #10 you sayed, you used a wrong url - might it be, it was this?

**Comment by allanpaiste** [comment]
how come this issue was closed and README does not still state an example of how local patches are being used. Following through the discussion around this topic did not shed any more light on this either. What is the proper composer.json setup when I want to apply/include a local patch file?
