### ISSUE TITLE
Don't try to reapply patches on composer update

### ISSUE THREAD

**Issue by pcambra** [netresearch/composer-patches-plugin#6]
When you've got a patch set and you add a new patch, composer update will try to patch all the set, instead of skipping those already applied, thus failing in the process.

A workaround for this would be to have a new package every time you add patches to the project but that's quite inconvenient.

**Comment by copitz** [comment]
Hi - thanks for your feedback!

> A workaround for this would be to have a new package every time you add patches
Have you tried to raise the version of the patch package instead? Then composer should uninstall the earlier patches prior to installing the new version.

**Comment by pcambra** [comment]
Thanks a lot for the feedback!

> Have you tried to raise the version of the patch package instead? Then composer should uninstall the earlier patches prior to installing the new version.

That's what I'm doing, example:
```
"type": "package",
  "package": {
    "name": "owner/package_name",
    "version": "1.0.0",
    "type": "patches",
    "require": {
      "netresearch/composer-patches-plugin": "~1.0"
    },
    "extra": {
      "patches": {
        "drupal/entityreference": {
          "7.1.x-dev": {
            "dc4196b4e97e11ff24e762d94864132e12daf7be": {
              "title": "Allow skipping entity access check when rendering field",
              "url": "https://www.drupal.org/files/issues/entityreference-skip-access-check-1967180-16.patch"
            }
          }
        },
        "drupal/features": {
          "7.2.2":[
            {
              "title": "Remove mtime from .info export (added by Drupal 7.33)",
              "url": "https://www.drupal.org/files/issues/2381739-features-mtime.patch"
            }
          ]
        }
      }
    }
  }
```
If I change  "version": "1.0.0" to     "version": "1.0.1" when I do composer update, patch is not reverted and tries to apply again

```
[Netresearch\Composer\Patches\PatchCommandException]                     
  Patch dc4196b4e97e11ff24e762d94864132e12daf7be failed!                   
  Error executing command "patch -f -p1 --no-backup-if-mismatch -r - -R":  
  patching file entityreference.module         
```

**Comment by pcambra** [comment]
On a side note, I've found that the "-r -" doesn't work for me (OSX) and using "--reject-file=/dev/null" might be safer?

**Comment by pcambra** [comment]
My environment was really messed up, I confirm that upgrading the version works and the patches are reverted and reapplied. 

Maybe this bit could be removed  from writePatchNotice as the revert is an action that I definitely would want to see in the log even if it's not verbose (specially when applying existing patches)
```
		if ($action == 'revert' && !$this->io->isVerbose()) {
			return;
		}

**Comment by dutchiexl** [comment]
@pcambra, I am having the same issue, how did you solve this ?
