### ISSUE TITLE
Allready deployed patches are redeployed

### ISSUE THREAD

**Issue by dutchiexl** [netresearch/composer-patches-plugin#9]
When I add a patch to the list, and update the version number, all previous patches are also ran.

How can I prevent this ?
<pre>
type": "package",
      "package": {
        "name": "cgk/patches",
        "version": "1.0.12",
        "type": "patches",
        "require": {
          "netresearch/composer-patches-plugin": "~1.0"
        },
        "extra": {
          "patches": {
            "drupal/domain": {
              "7.3.11": [
                {
                  "title": "Fixes the bootstrap problem",
                  "url": "https://www.drupal.org/files/issues/domain-domain-bootstrap-1342740-38.patch"
                }
              ]
            },
            "drupal/wysiwyg": {
              "7.2.2": [
                {
                  "title": "Fixes the ckeditor version not found problem",
                  "url": "https://www.drupal.org/files/wysiwyg-support_v4_ckeditor-1853550-73.patch"
                }
              ]
            },
            "drupal/lang_dropdown": {
              "7.2.5": [
                {
                  "title": "Fixes the jquery update ddslick issue.",
                  "url": "https://www.drupal.org/files/issues/lang_dropdown-ddslick-version-compare-2271459-6.patch"
                }
              ]
            },
            "drupal/nodequeue": {
              "7.2.0": [
                {
                  "title": "Fixes the apachesolr_mark_node issue.",
                  "url": "https://www.drupal.org/files/nodequeue-7.x-2.0-beat1-apachesolr-1425326-6028750.patch"
                }
              ]
            }
          }
</pre>

**Comment by copitz** [comment]
The patches __should__ be applied again but the already applied patches should be reverted automatically before the update. Could it be that composer doesn't have the old version of your patch package and thus can not know which previous patches to revert?

**Comment by copitz** [comment]
Closing this issue, as there was no reply so far. Feel free to reopen it if required
